version: "3.5"

x-logging:
  &default-logging
    driver: "json-file"
    options:
      max-size: "5m"
      max-file: "2"

services:
  telegraf:
    container_name: telegraf
    image: telegraf:1.11.3-alpine
    labels:
      - container.monitoring.app=telegraf
    logging: *default-logging
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
      - TELEGRAF_ENV=${TELEGRAF_ENV}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
    volumes:
      - ./telegraf/config:/etc/telegraf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc:/host/etc:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/telegraf/root:ro # monitor disk usage
    privileged: true
    network_mode: host
